server:
  port: ${PORT}
  servlet:
    context-path: "/ead-authuser/"

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}

ead:
  api:
    url:
      course: "http://ead-course-service/ead-course"
  broker:
    exchange:
      userEvent: ead.userevent

authuser:
  refreshScope:
    name: Davi Wesley Freitas Holanda

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s
